services:
  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    mem_reservation: 2g
    mem_limit: 8g
    environment:
      POSTGRES_PASSWORD: "s74ftUhDTH"
    volumes:
      - "db:/var/lib/postgresql/data"

  # backend:
  # TODO this will run the scrapers, optionally fetching the Excel files as well
  # frontend:
  # TODO this will serve the website, based on the DB

volumes:
  db:
